### ISSUE TITLE
[DB] База даних Todo

### ISSUE THREAD

**Issue by RomanYanchuk** [Programming-Engineering-Pmi-33/Music-Quiz#12]
**Опис**

- Прикріпити _.txt_ файл з інформацією для розгортання бази даних.

- Оновити базу даних відповідно до оновленої UML діаграми.

**Comment by ghost** [comment]
Оновив команди та створив файл з командами для створення таблиць в базі даних.
[create_db_tables.sql](https://github.com/Programming-Engineering-Pmi-33/Music-Quiz/blob/master/create_db_tables.sql)

**Comment by loompoor** [comment]
Перевірив файл create_db_tables.sql та базу даних, таблиці оновлені
![image](https://user-images.githubusercontent.com/44877484/94366634-42e75d80-00e2-11eb-8e75-1297924a5966.png)

**Comment by loompoor** [comment]
Додати поле id до таблиці genres.

**Comment by ghost** [comment]
До таблиці **genres** додав поле **id**, а також додав відповідне поле **genre_id** до таблиці **quizzes**.
Редагував SQL [команди](https://github.com/Programming-Engineering-Pmi-33/Music-Quiz/blob/feature/db-test-project/create_db_tables.sql) для створення таблиць.

**Comment by loompoor** [comment]
Перевірив зміни у файлі create_db_tables.sql.
