### ISSUE TITLE
[DB] Створити та налаштувати Console App проєкт

### ISSUE THREAD

**Issue by loompoor** [Programming-Engineering-Pmi-33/Music-Quiz#13]
**Мотивація**
Для того, щоб почати працювати з базою даних на проєкті нам необхідний тестовий консольний застосунок.

**Опис**

- [x]  Створити окрему гілку _feature/db-test-project_, в якій буде зберігатись тестовий проект

- [x] Створити консольний проєкт на базі .NET Core версії 3.1

- [x] Налаштувати проєкт для роботи з Entity Framework Core версії 3.1

**Критерій прийняття**

-  Створена окрема гілка з назвою _feature/db-test-project_

-  Присутній консольний проект з відповідною версією .NET Core та EF

-  Проєкт готовий до підключення бази даних та подальших дій

- Присутній pull request до гілки  _feature/db-test-project_

**Comment by RomanYanchuk** [comment]
**Результати**

- Створений проєкт на .NET Core (3.1)

- Референси:

>  _Npgsql.EntityFrameworkCore.PostgreSQL_ (3.1.4) - для роботи з СКБД PostgreSQL

> _Microsoft.Extensions.Configuration.Json_ (3.1.8) - для винесення специфічних налаштувань в окремий .json файл

> _Microsoft.EntityFrameworkCore.Tools_ (3.1.8) - для роботи з міграціями

- appsettings.json доданий в .gitignore

**Comment by loompoor** [comment]
Провів рев'ю комітів, змерджив гілки.
