### ISSUE TITLE
[DB] Створити моделі

### ISSUE THREAD

**Issue by loompoor** [Programming-Engineering-Pmi-33/Music-Quiz#14]
**Мотивація:**
Для того, щоб почати працювати з базою даних на проєкті нам необхідний тестовий консольний застосунок.

**Опис:**

- [x] Створити моделі, які відповідають створеній базі даних

- [x] Пов'язати моделі між собою

**Критерій прийняття:**

- Присутні моделі, відповідають створеній базі даних

- Присутні відповідні зв'язки між моделями

- Присутній _pull request_ до _feature/db-test-project_

**Comment by loompoor** [comment]
[Pull request](https://github.com/Programming-Engineering-Pmi-33/Music-Quiz/pull/17) готовий до рев'ю

**Comment by ghost** [comment]
Зробив рев'ю [pull request](https://github.com/Programming-Engineering-Pmi-33/Music-Quiz/pull/17).
