### ISSUE TITLE
[DB] Створити функції для заповнення та перевірки бази даних

### ISSUE THREAD

**Issue by loompoor** [Programming-Engineering-Pmi-33/Music-Quiz#15]
**Мотивація:**
Для початку розробки та тестування нам необхідні тестові дані в нашій базі.

**Опис:**
 - [x] Написати функцію для заповнення таблиць тестовими даними
 - [x] Написати функцію яка виводить дані з бази даних у консоль
 - [x] Протестувати роботу функції на нашій базі

**Критерій прийняття:**
 - Clean code
 - База наповнена тестовими даними
 - Присутній _pull request_ до _feature/db-test-project_

**Comment by ghost** [comment]
[pull request](https://github.com/Programming-Engineering-Pmi-33/Music-Quiz/pull/18) готовий до перегляду.

**Comment by RomanYanchuk** [comment]
Провів рев'ю. Зауважень немає.

**Comment by RomanYanchuk** [comment]
To Do: 

- Зробити метод для заповнення тестовими даними - в кожну таблицю 30-50 рядків.

- Протестувати функціонал

**Comment by ghost** [comment]
Написав потрібні методи для генерації даних і занесення їх в БД. Завдання готове до рев'ю.
