### ISSUE TITLE
[DB] Створити скріпт для оновлення бази даних

### ISSUE THREAD

**Issue by loompoor** [Programming-Engineering-Pmi-33/Music-Quiz#23]
**Мотивація**
Щоб спростити оновлення бази даних при додаванні міграцій, нам необхідний скріпт і/або інструкція в _Readme.md_.

**Опис**

- [x] Створити скріпт (.sh/.ps) який буде оновлювати базу даних відповідно до створених міграцій.

- [x] Додати інструкцію стосовно додавання нових міграцій та оновлення бази.

**Критерій прийняття**

- Присутній робочий скріпт.

- Присутні інструкції у _Readme.md_.

**Comment by RomanYanchuk** [comment]
Завдання готове до рев'ю

**Comment by ghost** [comment]
Запустив і перевірив [скріпт](https://github.com/Programming-Engineering-Pmi-33/Music-Quiz/blob/feature/23-add-db-script/sandbox/DbTestProject/update-database.sh) для оновлення БД. Скріпт працює правильно і виконує задане завдання.
