### ISSUE TITLE
[DB] Видалити таблицю AppRating,  перемістити вміст у таблицю User

### ISSUE THREAD

**Issue by RomanYanchuk** [Programming-Engineering-Pmi-33/Music-Quiz#24]

**Comment by ghost** [comment]
Видалив модель AppRating. Замість неї додав поле AppRating (тип int) в модель [User](https://github.com/Programming-Engineering-Pmi-33/Music-Quiz/blob/feature/24-remove-AppRating/sandbox/DbTestProject/Models/User.cs).
Завдання готове до рев'ю.

**Comment by RomanYanchuk** [comment]
Перевірив, без зауважень.
