### ISSUE TITLE
[DB] Many-to-many без зв'язної таблиці

### ISSUE THREAD

**Issue by RomanYanchuk** [Programming-Engineering-Pmi-33/Music-Quiz#25]
**Опис**

- [x] З'ясувати чи є можливість у **EF Core** реалізувати _many-to-many_ без зв'язної таблиці.

- Якщо є позитивна відповідь на завдання вище, тоді:

   1.  Видалити зв'язну таблицю `QuizSong`.

   1.  Замість `List<QuizSong>` використати `List<Quiz>` i `List<Song>` у таблицях Song i List відповідно

- Інакше, дати відповідь у коментарях, з посиланням на джерело.

**Comment by RomanYanchuk** [comment]
**QuizSong**

- У EF6 _(для .NET Framework)_ можна не використовувати для відношень _many-to-many_ зв'язну таблицю.
- У EF Core ця можливість не підтримується, отже потрібно додати зв'язну таблицю.

![image](https://user-images.githubusercontent.com/53482108/97081610-26b8dc80-160c-11eb-94af-21bc87ce9afa.png)



Дані з джерела: [Microsoft Docs](https://docs.microsoft.com/en-us/ef/efcore-and-ef6/)

**Comment by RomanYanchuk** [comment]
Завдання готове до рев'ю

**Comment by loompoor** [comment]
Завдання виконане
