### ISSUE TITLE
[DB] Визначити спосіб хешування паролів (унікальний для однакових)

### ISSUE THREAD

**Issue by RomanYanchuk** [Programming-Engineering-Pmi-33/Music-Quiz#28]

**Comment by loompoor** [comment]
Для виконання завдання використав [PBKDF2](https://en.wikipedia.org/wiki/PBKDF2) який відноситься до [Public-Key Cryptography Standards](https://en.wikipedia.org/wiki/PKCS).
Результатом роботи є методи для хешування паролю та його перевірки.

**Comment by RomanYanchuk** [comment]
Перевірив.
