### ISSUE TITLE
[Setup] Додати базовий функціонал в StorageLayer

### ISSUE THREAD

**Issue by RomanYanchuk** [Programming-Engineering-Pmi-33/Music-Quiz#31]
**Мотивація**
Щоб мати змогу розробляти основний функціонал нашого застосунку, нам необхідний рівень обміну даних з базою даних.

**Опис**

- [x] Створити контекст бази даних.

- [x] Додати моделі.

- [x] Додати зв'язки між моделями.

- [x] Додати початкову міграцію (Code First). Міграцію зберегти за шляхом _**MusicalQuiz/StorageLayer/Migrations**_.

- [x] Додати методи для можливості тестування **StorageLayer** (тимчасово).

- [x] Змінити **Readme.md** файл.

**Критерій прийняття**

- Створено контекст, моделі, зв'язки.

- Присутня міграція, за вказаним шляхом.

- Є можливість протестувати.

- В **Readme.md** файлі є інформація про додавання міграцій, встановлення/оновлення бази даних

**Comment by RomanYanchuk** [comment]
Завдання готове до перевірки.

**Comment by ghost** [comment]
Завдання перевірив. Зауважень немає.
