### ISSUE TITLE
[DB] Схема бази даних (UML діаграма)

### ISSUE THREAD

**Issue by RomanYanchuk** [Programming-Engineering-Pmi-33/Music-Quiz#6]
**Мотивація:**
Щоб правильно створити базу даних для нашого застосунку, розуміння всіх зв'язків та відношень, необхідна її схема.

**Опис:**

- [x] Визначити які дані будуть зберігатися в базі даних.

- [x] Для кожної таблиці вказати дані, які там будуть зберігатися, типи.
- [x] Створити залежності між таблицями 
- [x] Розробити схему бази даних з таблицями у вигляді відповідної UML діаграми.

**Критерій прийняття**

1. Дані, які зберігаються у базі даних відповідають вимогам [usecase діаграми](https://github.com/Programming-Engineering-Pmi-33/Music-Quiz/wiki/Usecase-%D0%B4%D1%96%D0%B0%D0%B3%D1%80%D0%B0%D0%BC%D0%B0) та [функціоналу](https://github.com/Programming-Engineering-Pmi-33/Music-Quiz/wiki/%D0%A4%D1%83%D0%BD%D0%BA%D1%86%D1%96%D0%BE%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D1%96-%D1%82%D0%B0-%D0%BD%D0%B5%D1%84%D1%83%D0%BD%D0%BA%D1%86%D1%96%D0%BE%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D1%96-%D0%B2%D0%B8%D0%BC%D0%BE%D0%B3%D0%B8-%D0%B4%D0%BE-%D0%BF%D1%80%D0%BE%D1%94%D0%BA%D1%82%D1%83).

1. Для кожної таблиці вказані типи даних, які там зберігаються, зв'язки між таблицями.

1. Схема бази даних (UML діаграма) прикріплена у коментарях.

**Додаткова інформація**

1. Після рев'ю прикріплені матеріали перемістити у [wiki](https://github.com/Programming-Engineering-Pmi-33/Music-Quiz/wiki/UML-%D0%B4%D1%96%D0%B0%D0%B3%D1%80%D0%B0%D0%BC%D0%B0).

**Comment by loompoor** [comment]
### Дані які будуть зберігатися в базі даних(відповідно до функціональних вимог проєкту):

- Дані користувача:
  - Логін
  - Пароль
- Дані тесту:
  - Посилання на користувача
  - Назва
  - Жанр
  - Список пісень
  - Час відтворення
  - Час на відповідь
- Дані рейтингової таблиці:
  - Посилання на користувача
  - Посилання на тест
  - Рейтинг (бали)
- Дані рейтингу застосунку
  - Інформація про користувача (посилання на користувача)
  - Оцінка

**Comment by loompoor** [comment]
[UML Diagram](https://drive.google.com/file/d/1Pg3zKtQoNkK4d4-DiKqtQRCMhH6XAFyc/view?usp=sharing)
Посилання на діаграму

**Comment by ghost** [comment]
Переглянув та перевірив UML діаграму.
