### ISSUE TITLE
[DB] Створити базу даних

### ISSUE THREAD

**Issue by RomanYanchuk** [Programming-Engineering-Pmi-33/Music-Quiz#7]
**Мотивація:**
Для початку розробки нашого застосунку, необхідна налаштована база даних.

**Опис:**

- [x] Вибрати провайдера для бази даних.

- [x] Створити базу даних.

- [x] Додати необхідні таблиці, зв'язки.

**Критерій прийняття**

1. Створена база даних.

1. Присутні таблиці та зв'язки відповідно до [UML діаграми](https://github.com/Programming-Engineering-Pmi-33/Music-Quiz/wiki/UML-%D0%B4%D1%96%D0%B0%D0%B3%D1%80%D0%B0%D0%BC%D0%B0).

**Comment by ghost** [comment]
Разом з командою обрали систему керуванням БД - PostgreSQL, а також хмарну платформу для зберігання БД - Heroku.
На хмарній платформі Heroku створив базу даних.
За створеною [UML діаграмою](https://github.com/Programming-Engineering-Pmi-33/Music-Quiz/wiki/UML-%D0%B4%D1%96%D0%B0%D0%B3%D1%80%D0%B0%D0%BC%D0%B0) створив необхідні таблиці.

![created_database_on_heroku](https://user-images.githubusercontent.com/19283701/94201686-07bc1300-fec5-11ea-8589-cc0f909ac1bb.png)
![sql_commands](https://user-images.githubusercontent.com/19283701/94201690-0854a980-fec5-11ea-96e3-e8bf224acaaf.png)

**Comment by RomanYanchuk** [comment]
В таблиці **Quizzes** відповідно до [UML діаграми](https://github.com/Programming-Engineering-Pmi-33/Music-Quiz/wiki/UML-%D0%B4%D1%96%D0%B0%D0%B3%D1%80%D0%B0%D0%BC%D0%B0) повинні бути ще 2 поля: **answer_time** i **play_time**
Завдання повернуто.

**Comment by ghost** [comment]
До таблиці **quizzes** додав стовпці **play_time** і **answer_time**.
![photo_2020-09-25_12-11-22](https://user-images.githubusercontent.com/19283701/94251915-e80c0580-ff2b-11ea-9f43-965c236c59d5.jpg)

**Comment by RomanYanchuk** [comment]
Перевірив наявність таблиць та зв'язків відповідно до UML діаграми.
