### ISSUE TITLE
[DB] Diagram Todo

### ISSUE THREAD

**Issue by RomanYanchuk** [Programming-Engineering-Pmi-33/Music-Quiz#9]
**Опис**

- Винести **songs** з таблиці **Quiz** в окрему таблицю.

- Вирішити питання з ключами

**Comment by loompoor** [comment]
Оновив діаграму:
[Diagram](https://drive.google.com/file/d/1aVZcezS6YM5ZStGbIwUwE3xWhGAZLlI_/view?usp=sharing)

**Comment by loompoor** [comment]
Виправив помилку:
[Diagram](https://drive.google.com/file/d/14DSFSj90G94_tCAGyqqxEVbcJfk0e-5r/view?usp=sharing)

**Comment by ghost** [comment]
Діаграма виправлена відповідно до зауважень.
